import React, { useState } from 'react';
import { Sparkles, ThumbsUp, Star, ShoppingBag } from 'lucide-react';
import type { UserProfile, OccasionType, ColorCombo, RetailProduct } from '../types/fashion';
import { COLOR_COMBINATIONS, RETAIL_PRODUCTS } from '../data/fashionData';

interface AIEngineViewProps {
  userProfile: UserProfile;
  onSelectProduct: (product: RetailProduct) => void;
  onNavigateTab: (tab: string) => void;
}

export const AIEngineView: React.FC<AIEngineViewProps> = ({
  userProfile,
  onSelectProduct,
  onNavigateTab,
}) => {
  const [selectedOccasion, setSelectedOccasion] = useState<OccasionType>('Work');
  const [combos, setCombos] = useState<ColorCombo[]>(COLOR_COMBINATIONS);

  const filteredCombos = combos.filter((c) => c.occasion === selectedOccasion || selectedOccasion === 'Work');

  const handleUpvoteCombo = (comboId: string) => {
    setCombos((prev) =>
      prev.map((c) => {
        if (c.id === comboId) {
          const newVotes = c.votesCount + 1;
          const newRating = Math.min(5.0, Number((c.rating + 0.01).toFixed(2)));
          return { ...c, votesCount: newVotes, rating: newRating, userVote: 5 };
        }
        return c;
      })
    );
  };

  return (
    <div className="space-y-8 animate-fadeIn">
      
      {/* Hero Header Card */}
      <div className="glass-panel-gold rounded-3xl p-6 sm:p-8 relative overflow-hidden">
        <div className="absolute -right-12 -top-12 w-64 h-64 bg-gradient-to-br from-amber-500/20 via-rose-500/10 to-transparent rounded-full blur-3xl pointer-events-none" />
        
        <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6 relative z-10">
          <div className="space-y-2 max-w-2xl">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-amber-400/10 border border-amber-400/30 text-amber-300 text-xs font-semibold">
              <Sparkles className="w-3.5 h-3.5" />
              <span>AI Styling Engine • Active Profile Match</span>
            </div>
            <h1 className="text-3xl sm:text-4xl font-serif font-bold text-white tracking-tight">
              Personalized Outfit Matrix for <span className="gradient-text-gold">{userProfile.name}</span>
            </h1>
            <p className="text-sm text-slate-300">
              Generated by combining your <strong className="text-amber-300">{userProfile.skinTone}</strong> undertones and <strong className="text-amber-300">{userProfile.bodyShape}</strong> silhouette rules with 42,000+ community votes on color harmony.
            </p>
          </div>

          {/* Active Profile Pill */}
          <div className="bg-slate-900/80 border border-white/10 p-4 rounded-2xl text-xs space-y-2 text-slate-300 min-w-[240px]">
            <div className="flex justify-between items-center pb-2 border-b border-white/10">
              <span className="font-bold text-white">Body Vector</span>
              <span className="text-amber-400 font-semibold">{userProfile.bodyShape}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-400">Skin Undertone:</span>
              <span className="text-rose-300 font-medium">{userProfile.undertone} Palette</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-400">Match Confidence:</span>
              <span className="text-emerald-400 font-bold">98.4%</span>
            </div>
          </div>
        </div>
      </div>

      {/* Occasion Selector Bar */}
      <div className="flex items-center justify-between gap-4 overflow-x-auto pb-2">
        <div className="flex items-center gap-2 bg-slate-900/80 p-1.5 rounded-2xl border border-white/10">
          {(['Work', 'Casual', 'Date night', 'Formal', 'Party', 'Travel'] as OccasionType[]).map((occ) => (
            <button
              key={occ}
              onClick={() => setSelectedOccasion(occ)}
              className={`px-4 py-2 rounded-xl text-xs font-bold transition-all whitespace-nowrap ${
                selectedOccasion === occ
                  ? 'bg-gradient-to-r from-amber-500 to-rose-500 text-slate-950 shadow-md shadow-amber-500/20'
                  : 'text-slate-400 hover:text-white hover:bg-white/5'
              }`}
            >
              {occ}
            </button>
          ))}
        </div>

        <button
          onClick={() => onNavigateTab('color-voting')}
          className="flex items-center gap-2 text-xs font-semibold text-amber-400 hover:text-amber-300 bg-amber-400/10 hover:bg-amber-400/20 px-3.5 py-2 rounded-xl border border-amber-400/30 transition-all whitespace-nowrap"
        >
          <ThumbsUp className="w-3.5 h-3.5" />
          <span>Vote on New Combos</span>
        </button>
      </div>

      {/* Recommended Outfit Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {filteredCombos.map((combo) => (
          <div key={combo.id} className="glass-card rounded-3xl overflow-hidden flex flex-col justify-between">
            {/* Image Preview & Badges */}
            <div className="relative h-64 overflow-hidden group">
              <img
                src={combo.exampleImageUrl}
                alt={combo.title}
                className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-950/20 to-transparent" />
              
              {/* Badge Overlay */}
              <div className="absolute top-3 left-3 flex gap-2">
                <span className="badge-top-rated px-2.5 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider flex items-center gap-1 shadow-md">
                  <Star className="w-3 h-3 fill-amber-400 text-amber-400" />
                  <span>{combo.rating} ({combo.votesCount.toLocaleString()} votes)</span>
                </span>
              </div>

              {/* Color Swatch Overlay */}
              <div className="absolute bottom-3 left-3 right-3 flex items-center justify-between bg-slate-950/80 backdrop-blur-md p-2.5 rounded-2xl border border-white/10">
                <div className="flex items-center gap-2">
                  {combo.colors.map((c, i) => (
                    <div
                      key={i}
                      className="w-6 h-6 rounded-full border border-white/20 shadow-inner group-hover:scale-110 transition-transform"
                      style={{ backgroundColor: c.hex }}
                      title={`${c.name} (${c.hex})`}
                    />
                  ))}
                </div>
                <span className="text-[10px] text-slate-300 font-medium">{combo.subType}</span>
              </div>
            </div>

            {/* Content & Actions */}
            <div className="p-5 space-y-4 flex-1 flex flex-col justify-between">
              <div>
                <h3 className="font-serif font-bold text-lg text-white">{combo.title}</h3>
                <p className="text-xs text-slate-400 mt-1">
                  Validated for <strong className="text-slate-200">{combo.occasion}</strong> occasion. Matches your <span className="text-amber-300 font-medium">{userProfile.skinTone}</span> undertones.
                </p>
              </div>

              {/* Sample Product Matches from Commerce Catalogue */}
              <div className="space-y-2 pt-2 border-t border-white/10">
                <span className="text-[10px] uppercase font-bold tracking-wider text-slate-400 block">
                  Indexed Retailer Matches
                </span>
                <div className="grid grid-cols-2 gap-2">
                  {RETAIL_PRODUCTS.slice(0, 2).map((prod) => (
                    <button
                      key={prod.id}
                      onClick={() => onSelectProduct(prod)}
                      className="flex items-center gap-2 p-2 rounded-xl bg-slate-900/80 hover:bg-slate-800 border border-white/5 hover:border-amber-400/30 text-left transition-all"
                    >
                      <img src={prod.imageUrl} alt={prod.title} className="w-8 h-8 rounded-lg object-cover" />
                      <div className="overflow-hidden">
                        <div className="text-[11px] font-semibold text-white truncate">{prod.title}</div>
                        <div className="text-[10px] text-amber-400 font-bold">${prod.price}</div>
                      </div>
                    </button>
                  ))}
                </div>
              </div>

              {/* Interactive Upvote & Commerce Buttons */}
              <div className="flex items-center gap-2 pt-2">
                <button
                  onClick={() => handleUpvoteCombo(combo.id)}
                  className={`flex-1 flex items-center justify-center gap-1.5 py-2.5 rounded-xl text-xs font-bold transition-all border ${
                    combo.userVote
                      ? 'bg-amber-400/20 text-amber-300 border-amber-400/50'
                      : 'bg-white/5 hover:bg-white/10 text-slate-200 border-white/10'
                  }`}
                >
                  <ThumbsUp className={`w-3.5 h-3.5 ${combo.userVote ? 'fill-amber-400 text-amber-400' : ''}`} />
                  <span>{combo.userVote ? 'Voted' : 'Rate Combo'}</span>
                </button>

                <button
                  onClick={() => onNavigateTab('stock-locator')}
                  className="flex-1 flex items-center justify-center gap-1.5 bg-gradient-to-r from-amber-500 to-rose-500 hover:from-amber-400 hover:to-rose-400 text-slate-950 font-bold py-2.5 rounded-xl text-xs shadow-md shadow-amber-500/10 transition-all"
                >
                  <ShoppingBag className="w-3.5 h-3.5" />
                  <span>Find Stock & Budget</span>
                </button>
              </div>

            </div>
          </div>
        ))}
      </div>

    </div>
  );
};
